name: amorphouspy-structural-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - ase
  - numba
  - numpy
  - pandas
  - scipy
  - networkx
  - pymatgen
  - plotly
  - matplotlib
  - jupyterlab
  - pip
  - pip:
    - pydantic
    - PyMCubes
    - amorphouspy
